include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    avoid_print: false # Allowed for debug
    use_key_in_widget_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_this: true
    prefer_typing_uninitialized_variables: true
