#!/usr/bin/env bash
#
# Creates the Play upload keystore and the gitignored key.properties that
# app/build.gradle.kts reads.
#
# Run ONCE. The keystore lives OUTSIDE the repo and is never committed.
#
# If you lose this file you can still ship updates, because Play App Signing
# holds the real app signing key and Google can reset a lost upload key — but
# that is a support ticket and days of delay. Back it up anyway.
#
set -euo pipefail

KEYSTORE="${KEYSTORE:-$HOME/salom-ai-upload.keystore}"
ALIAS="${ALIAS:-salom-ai-upload}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROPS="$PROJECT_DIR/key.properties"

if [ -f "$KEYSTORE" ]; then
  echo "Refusing to overwrite existing keystore: $KEYSTORE" >&2
  echo "Delete it deliberately, or set KEYSTORE=<path> to use another location." >&2
  exit 1
fi

# Prefer the Homebrew JDK 17 that the Gradle build also uses.
if [ -x "/opt/homebrew/opt/openjdk@17/bin/keytool" ]; then
  KEYTOOL="/opt/homebrew/opt/openjdk@17/bin/keytool"
else
  KEYTOOL="$(command -v keytool)"
fi

PASSWORD="${PASSWORD:-$(openssl rand -base64 24 | tr -d '/+=' | head -c 28)}"

"$KEYTOOL" -genkeypair -v \
  -keystore "$KEYSTORE" \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 4096 \
  -validity 10000 \
  -storepass "$PASSWORD" \
  -keypass "$PASSWORD" \
  -dname "CN=Salom AI, OU=Mobile, O=Fera Tech, L=Tashkent, C=UZ"

umask 077
cat > "$PROPS" <<EOF
# Generated by tools/create-keystore.sh — gitignored, never commit.
storeFile=$KEYSTORE
storePassword=$PASSWORD
keyAlias=$ALIAS
keyPassword=$PASSWORD
EOF
chmod 600 "$PROPS"

echo
echo "Keystore : $KEYSTORE"
echo "Props    : $PROPS  (chmod 600, gitignored)"
echo
echo "Upload-key SHA-256 (for reference; assetlinks.json needs the PLAY APP SIGNING"
echo "fingerprint from Play Console, not this one):"
"$KEYTOOL" -list -v -keystore "$KEYSTORE" -alias "$ALIAS" -storepass "$PASSWORD" \
  | grep "SHA256:"
echo
echo "!! BACK UP $KEYSTORE AND THE PASSWORD IN key.properties (1Password) NOW."
