import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:salom_ai/router.dart';

final localeProvider = StateNotifierProvider<LocaleNotifier, String>((ref) {
  final prefs = ref.watch(sharedPreferencesProvider);
  return LocaleNotifier(prefs);
});

class LocaleNotifier extends StateNotifier<String> {
  final SharedPreferences _prefs;

  LocaleNotifier(this._prefs) : super(_prefs.getString('preferredLanguageCode') ?? 'uz');

  void setLocale(String code) {
    state = code;
    _prefs.setString('preferredLanguageCode', code);
  }

  String translate(String key) {
    final translations = _allTranslations[state] ?? _allTranslations['uz']!;
    return translations[key] ?? key;
  }
}

extension LocalizationExtension on WidgetRef {
  String tr(String key) {
    final locale = watch(localeProvider);
    final translations = _allTranslations[locale] ?? _allTranslations['uz']!;
    return translations[key] ?? key;
  }
}

final Map<String, Map<String, String>> _allTranslations = {
  "uz": {
    "settings": "Sozlamalar",
    "profile_card_default_user": "Salom foydalanuvchi",
    "profile_card_guest": "Mehmon",
    "phone_not_identified": "Telefon raqam aniqlanmagan",
    "subscription": "Obuna",
    "current_plan": "Joriy reja",
    "free": "Bepul",
    "loading": "Yuklanmoqda...",
    "help": "Yordam",
    "send_feedback": "Fikr-mulohaza yuborish",
    "language": "Til",
    "uzbek": "O\u2018zbekcha",
    "russian": "Ruscha",
    "english": "Inglizcha",
    "login_info": "Kirish ma\u2018lumotlari",
    "logout": "Chiqish",
    "delete_account": "Hisobni o'chirish",
    "deleting": "O'chirilmoqda...",
    "delete_account_title": "Hisobni o'chirish",
    "delete_account_message": "Hisobingizni butunlay o'chirishni xohlaysizmi? Bu amal barcha suhbatlar, xabarlar va ma'lumotlaringizni butunlay o'chiradi. Bu amalni bekor qilib bo'lmaydi!",
    "cancel": "Bekor qilish",
    "delete": "O'chirish",
    "error": "Xatolik",
    "ok": "OK",
    "pro_features": "Pro imkoniyatlar",
    "unlimited_conv": "Cheklovsiz muloqot va ko'proq imkoniyatlar",
    "subscriptions": "Obunalar",
    "valid_until": "Amal qilish muddati",
    "active": "Faol",
    "choose": "Tanlash",
    "no_perks": "Imtiyozlar mavjud emas",
    "month_count": "/ oyiga",
    "uzbek_cyrl": "O\u2018zbekcha (Kirill)",
    // New keys
    "chat": "Suhbat",
    "voice_chat": "Ovozli suhbat",
    "notifications": "Bildirishnomalar",
    "search": "Qidirish",
    "new_chat": "Yangi suhbat",
    "upgrade_to_pro": "Pro ga o'tish",
    "unlock_all_features": "Barcha imkoniyatlarni oching",
    "no_results": "Natija topilmadi",
    "message_hint": "Xabar yozing...",
    "image_prompt_hint": "Rasm tavsifini yozing...",
    "photo": "Rasm",
    "document": "Hujjat",
    "copy": "Nusxalash",
    "share": "Ulashish",
    "select_model": "Model tanlash",
    "image_mode": "Rasm rejimi",
    "generating_image": "Rasm yaratilmoqda...",
    "voice_connecting": "Ulanmoqda...",
    "voice_settings": "Ovoz sozlamalari",
    "voice_type": "Ovoz turi",
    "voice_role": "Rol",
    "apply": "Qo'llash",
    "usage_stats": "Foydalanish statistikasi",
    "messages": "Xabarlar",
    "images": "Rasmlar",
    "files": "Fayllar",
    "voice_minutes": "Ovozli daqiqalar",
    "per_model_usage": "Modellar bo'yicha",
    "no_notifications": "Bildirishnomalar yo'q",
    "no_notifications_desc": "Yangi bildirishnomalar bu yerda paydo bo'ladi",
    "paywall_unlimited_messages": "Cheksiz xabarlar",
    "paywall_unlimited_messages_desc": "Har kuni cheksiz suhbat qiling",
    "paywall_advanced_models": "Ilg'or modellar",
    "paywall_advanced_models_desc": "GPT-4, Claude va boshqa kuchli modellar",
    "paywall_voice_chat": "Ovozli suhbat",
    "paywall_voice_chat_desc": "Real vaqtda ovozli muloqot",
    "paywall_image_gen": "Rasm yaratish",
    "paywall_image_gen_desc": "Sun'iy intellekt bilan rasm yarating",
    "paywall_later": "Keyinroq",
    "quota_exceeded": "Kunlik limit tugadi. Pro ga o'ting!",
    "session_expired": "Sessiya muddati tugadi. Qayta kiring.",
    "network_error": "Internet aloqasi yo'q",
    "retry": "Qayta urinish",
    "delete_conversation": "Suhbatni o'chirish",
    "delete_conversation_confirm": "Bu suhbatni o'chirishni xohlaysizmi?",
  },
  "ru": {
    "settings": "Настройки",
    "profile_card_default_user": "Привет, пользователь",
    "profile_card_guest": "Гость",
    "phone_not_identified": "Номер телефона не определен",
    "subscription": "Подписка",
    "current_plan": "Текущий план",
    "free": "Бесплатно",
    "loading": "Загрузка...",
    "help": "Помощь",
    "send_feedback": "Отправить отзыв",
    "language": "Язык",
    "uzbek": "Узбекский",
    "russian": "Русский",
    "english": "Английский",
    "login_info": "Данные для входа",
    "logout": "Выйти",
    "delete_account": "Удалить аккаунт",
    "deleting": "Удаление...",
    "delete_account_title": "Удалить аккаунт",
    "delete_account_message": "Вы уверены, что хотите полностью удалить свой аккаунт? Это действие удалит все ваши чаты, сообщения и данные без возможности восстановления!",
    "cancel": "Отмена",
    "delete": "Удалить",
    "error": "Ошибка",
    "ok": "OK",
    "pro_features": "Pro возможности",
    "unlimited_conv": "Без ограничений и больше возможностей",
    "subscriptions": "Подписки",
    "valid_until": "Срок действия",
    "active": "Активный",
    "choose": "Выбрать",
    "no_perks": "Преимущества недоступны",
    "month_count": "/ месяц",
    "uzbek_cyrl": "Узбекский (Кириллица)",
    // New keys
    "chat": "Чат",
    "voice_chat": "Голосовой чат",
    "notifications": "Уведомления",
    "search": "Поиск",
    "new_chat": "Новый чат",
    "upgrade_to_pro": "Перейти на Pro",
    "unlock_all_features": "Откройте все возможности",
    "no_results": "Ничего не найдено",
    "message_hint": "Напишите сообщение...",
    "image_prompt_hint": "Опишите изображение...",
    "photo": "Фото",
    "document": "Документ",
    "copy": "Копировать",
    "share": "Поделиться",
    "select_model": "Выбрать модель",
    "image_mode": "Режим изображений",
    "generating_image": "Создание изображения...",
    "voice_connecting": "Подключение...",
    "voice_settings": "Настройки голоса",
    "voice_type": "Тип голоса",
    "voice_role": "Роль",
    "apply": "Применить",
    "usage_stats": "Статистика использования",
    "messages": "Сообщения",
    "images": "Изображения",
    "files": "Файлы",
    "voice_minutes": "Голосовые минуты",
    "per_model_usage": "По моделям",
    "no_notifications": "Нет уведомлений",
    "no_notifications_desc": "Новые уведомления появятся здесь",
    "paywall_unlimited_messages": "Безлимитные сообщения",
    "paywall_unlimited_messages_desc": "Общайтесь без ограничений каждый день",
    "paywall_advanced_models": "Продвинутые модели",
    "paywall_advanced_models_desc": "GPT-4, Claude и другие мощные модели",
    "paywall_voice_chat": "Голосовой чат",
    "paywall_voice_chat_desc": "Общение голосом в реальном времени",
    "paywall_image_gen": "Генерация изображений",
    "paywall_image_gen_desc": "Создавайте изображения с помощью ИИ",
    "paywall_later": "Позже",
    "quota_exceeded": "Дневной лимит исчерпан. Перейдите на Pro!",
    "session_expired": "Сессия истекла. Войдите снова.",
    "network_error": "Нет подключения к интернету",
    "retry": "Повторить",
    "delete_conversation": "Удалить чат",
    "delete_conversation_confirm": "Вы хотите удалить этот чат?",
  },
  "en": {
    "settings": "Settings",
    "profile_card_default_user": "Salom User",
    "profile_card_guest": "Guest",
    "phone_not_identified": "Phone number not identified",
    "subscription": "Subscription",
    "current_plan": "Current Plan",
    "free": "Free",
    "loading": "Loading...",
    "help": "Support",
    "send_feedback": "Send feedback",
    "language": "Language",
    "uzbek": "Uzbek",
    "russian": "Russian",
    "english": "English",
    "login_info": "Login Information",
    "logout": "Log out",
    "delete_account": "Delete Account",
    "deleting": "Deleting...",
    "delete_account_title": "Delete Account",
    "delete_account_message": "Are you sure you want to permanently delete your account? This action will delete all your conversations, messages, and data. This cannot be undone!",
    "cancel": "Cancel",
    "delete": "Delete",
    "error": "Error",
    "ok": "OK",
    "pro_features": "Pro Features",
    "unlimited_conv": "Unlimited conversations and more possibilities",
    "subscriptions": "Subscriptions",
    "valid_until": "Valid until",
    "active": "Active",
    "choose": "Choose",
    "no_perks": "No perks available",
    "month_count": "/ month",
    "uzbek_cyrl": "Uzbek (Cyrillic)",
    // New keys
    "chat": "Chat",
    "voice_chat": "Voice Chat",
    "notifications": "Notifications",
    "search": "Search",
    "new_chat": "New Chat",
    "upgrade_to_pro": "Upgrade to Pro",
    "unlock_all_features": "Unlock all features",
    "no_results": "No results found",
    "message_hint": "Type a message...",
    "image_prompt_hint": "Describe the image...",
    "photo": "Photo",
    "document": "Document",
    "copy": "Copy",
    "share": "Share",
    "select_model": "Select Model",
    "image_mode": "Image Mode",
    "generating_image": "Generating image...",
    "voice_connecting": "Connecting...",
    "voice_settings": "Voice Settings",
    "voice_type": "Voice Type",
    "voice_role": "Role",
    "apply": "Apply",
    "usage_stats": "Usage Statistics",
    "messages": "Messages",
    "images": "Images",
    "files": "Files",
    "voice_minutes": "Voice Minutes",
    "per_model_usage": "Per Model",
    "no_notifications": "No notifications",
    "no_notifications_desc": "New notifications will appear here",
    "paywall_unlimited_messages": "Unlimited Messages",
    "paywall_unlimited_messages_desc": "Chat without limits every day",
    "paywall_advanced_models": "Advanced Models",
    "paywall_advanced_models_desc": "GPT-4, Claude and other powerful models",
    "paywall_voice_chat": "Voice Chat",
    "paywall_voice_chat_desc": "Real-time voice conversations",
    "paywall_image_gen": "Image Generation",
    "paywall_image_gen_desc": "Create images with AI",
    "paywall_later": "Later",
    "quota_exceeded": "Daily limit reached. Upgrade to Pro!",
    "session_expired": "Session expired. Please log in again.",
    "network_error": "No internet connection",
    "retry": "Retry",
    "delete_conversation": "Delete Conversation",
    "delete_conversation_confirm": "Do you want to delete this conversation?",
  },
  "uz-Cyrl": {
    "settings": "Созламалар",
    "profile_card_default_user": "Салом фойдаланувчи",
    "profile_card_guest": "Меҳмон",
    "phone_not_identified": "Телефон рақам аниқланмаган",
    "subscription": "Обуна",
    "current_plan": "Жорий режа",
    "free": "Бепул",
    "loading": "Юкланмоқда...",
    "help": "Ёрдам",
    "send_feedback": "Фикр-мулоҳаза юбориш",
    "language": "Тил",
    "uzbek": "Ўзбекча",
    "russian": "Русча",
    "english": "Инглизча",
    "login_info": "Кириш маълумотлари",
    "logout": "Чиқиш",
    "delete_account": "Ҳисобни ўчириш",
    "deleting": "Ўчирилмоқда...",
    "delete_account_title": "Ҳисобни ўчириш",
    "delete_account_message": "Ҳисобингизни бутунлай ўчиришни хоҳлайсизми? Бу амал барча суҳбатлар, хабарлар ва маълумотларингизни бутунлай ўчиради. Бу амални бекор қилиб бўлмайди!",
    "cancel": "Бекор қилиш",
    "delete": "Ўчириш",
    "error": "Хатолик",
    "ok": "ОК",
    "pro_features": "Про имкониятлар",
    "unlimited_conv": "Чекловсиз мулоқот ва кўпроқ имкониятлар",
    "subscriptions": "Обуналар",
    "valid_until": "Амал қилиш муддати",
    "active": "Фаол",
    "choose": "Танлаш",
    "no_perks": "Имтиёзлар мавжуд эмас",
    "month_count": "/ ойига",
    "uzbek_cyrl": "Ўзбекча (Кирилл)",
    // New keys
    "chat": "Суҳбат",
    "voice_chat": "Овозли суҳбат",
    "notifications": "Билдиришномалар",
    "search": "Қидириш",
    "new_chat": "Янги суҳбат",
    "upgrade_to_pro": "Про га ўтиш",
    "unlock_all_features": "Барча имкониятларни очинг",
    "no_results": "Натижа топилмади",
    "message_hint": "Хабар ёзинг...",
    "image_prompt_hint": "Расм тавсифини ёзинг...",
    "photo": "Расм",
    "document": "Ҳужжат",
    "copy": "Нусхалаш",
    "share": "Улашиш",
    "select_model": "Модел танлаш",
    "image_mode": "Расм режими",
    "generating_image": "Расм яратилмоқда...",
    "voice_connecting": "Уланмоқда...",
    "voice_settings": "Овоз созламалари",
    "voice_type": "Овоз тури",
    "voice_role": "Рол",
    "apply": "Қўллаш",
    "usage_stats": "Фойдаланиш статистикаси",
    "messages": "Хабарлар",
    "images": "Расмлар",
    "files": "Файллар",
    "voice_minutes": "Овозли дақиқалар",
    "per_model_usage": "Моделлар бўйича",
    "no_notifications": "Билдиришномалар йўқ",
    "no_notifications_desc": "Янги билдиришномалар бу ерда пайдо бўлади",
    "paywall_unlimited_messages": "Чексиз хабарлар",
    "paywall_unlimited_messages_desc": "Ҳар куни чексиз суҳбат қилинг",
    "paywall_advanced_models": "Илғор моделлар",
    "paywall_advanced_models_desc": "GPT-4, Claude ва бошқа кучли моделлар",
    "paywall_voice_chat": "Овозли суҳбат",
    "paywall_voice_chat_desc": "Реал вақтда овозли мулоқот",
    "paywall_image_gen": "Расм яратиш",
    "paywall_image_gen_desc": "Сунъий интеллект билан расм яратинг",
    "paywall_later": "Кейинроқ",
    "quota_exceeded": "Кунлик лимит тугади. Про га ўтинг!",
    "session_expired": "Сессия муддати тугади. Қайта киринг.",
    "network_error": "Интернет алоқаси йўқ",
    "retry": "Қайта уриниш",
    "delete_conversation": "Суҳбатни ўчириш",
    "delete_conversation_confirm": "Бу суҳбатни ўчиришни хоҳлайсизми?",
  },
};
